### ISSUE TITLE
 Record button doesn't behave differently in photo mode (Remove photo mode)

### ISSUE THREAD

**Issue by dmoroni** [lholoubek/GameKeepr#11]
The record button should flash once instead of blink when it is in photo mode

**Comment by dmoroni** [comment]
The button behaves correctly in UI <> Model branch, but doesn't actually change the camera mode on the drone

**Comment by dmoroni** [comment]
This has been fixed and tested in the latest UI <> Model Branch.

**Comment by lholoubek** [comment]
@dmoroni  is this still a thing? Do we even want to support photo mode right now?

**Comment by dmoroni** [comment]
Not sure if this is still a bug I see how we could just ditch photo mode all together if we want for now...I'm fine with doing that until someone requests it.

**Comment by dmoroni** [comment]
fixed
